name: TM Forum Trouble Ticket API RI
version: 1.0.1
appVersion: 2.2.3
description: Lorem Ipsum
keywords:
- openapi
- tmforum
home: https://magento.com/
sources:
- https://github.com/bitnami/bitnami-docker-magento
maintainers:
- name: bitnami-bot
  email: containers@bitnami.com
engine: gotpl
icon: https://bitnami.com/assets/stacks/magento/img/magento-stack-110x117.png
